### ISSUE TITLE
Front office : mise à jour de la charte graphique 

### ISSUE THREAD

**Issue by delphinelrcl** [AtelierCartographie/eatlas#133]
Voici la liste des modifications apportées : 

### page d'accueil (p.26)
- [x] un nouveau fond est disponible (viz-home-bg.mp4)
- [x] supprimer le 0 de la rubrique “présentation”
- [x] ressources  > les expressions en gras sont cliquables
  (on laisse le lorem ipsum, cf. charte graphique)
- [x] ajouter la mention “en savoir plus” à la fin de chaque sous partie (à propos, l’équipe, le livre) ; en cliquant sur ce lien, le lecteur arrive directement au niveau de la  la sous-partie correspondant de la page “à propos”

### footer (p.27)
- [x] supprimer le 0 de présentation dans le sommaire
- [x] supprimer vidéos de la liste des ressources
- [x] ajouter le projet dans “ à propos”

### menu  (p.25) voir aussi #141 
- [x] un menu unique pour les versions mobile et pc sous forme de burger
  (a priori déjà fait, menu qui pousse la page visible sur PC et mobile)
- [x] ~~un menu qui se déplie pour afficher le détail de chaque rubrique quand on passe la souris dessus~~
- [x] un masque de recherche en haut à droite du titre symbolisé par une loupe ; quand on clique dessus, un bandeau s’affiche en dessous
  (sur toutes les pages à côté du titre)

### à propos (p.28-29)
- [x] l’équipe > prévoir un lien cliquable sur le nom et sur la vignette
- [x] nous contacter > lien vers un formulaire Google form (à créer)
- [x] le livre > lien  vers le site des presses de scpo

### mentions légales (p.30)
- [x] à rédiger (en attendant prendre les mentions légales de scpo)

### rubrique (p.17)
- [x] chaque titre de rubrique est accompagné d’un numéro sauf pour la rubrique Présentation
- [x] l’image utilisée pour le fonds sera différent selon les rubriques (https://github.com/AtelierCartographie/eatlas/issues/83)
- [x] la vidéo est remplacée par une photo
- [x] ajouter la possibilité de choisir la langue (fr/en) pour le champ description sur le même principe que pour les résumés des articles

### ressources (p.18-19)
- [x] supprimer la page références du Footer et du SideMenu

#### filtres (moteur de recherche) :
- [x] rappel des filtres : rubriques (chapitres), mots clés (afficher uniquement les 5 plus cités et faire suivre les autres de la mention “plus…” ou bien voir #148 ), date de publication (uniquement l’année), langue (à masquer pour le moment)
- [x] afficher les filtres à droite sur un écran mobile et les filtres à gauche sur pour les écrans PC
- [x] préciser le nombre de filtres utilisés entre (  )
- [x] ajouter un bouton “réinitialiser les filtres”
  (on vide le formulaire, il faut re-valider pour relancer la recherche sans filtre)

#### lexique (p.20) :
- [x] ajout d’un A to Z
- [x] le lien “lire la définition complète” fonctionne comme un accordéon qui s’ouvre ; il se déplie quand on clique dessus et se replie quand on clique à nouveau dessus (idem pour les références en bas de l'article).
  (ajouter l'animation)

#### résultats de recherche (p.21) : 
- [x] ordre d’affichage par défaut : définition du lexique (si elle existe), titre, mots clés, résumé / description (quelque soit le type de ressource) → #79 
- [x] nouvelle métadonnée pour les types photo, vidéo, carte (p. 22-14) : le champ “source” non obligatoire (article ou focus lié) permet de préciser où cette ressource a été utilisée ; l’affichage est le même que pour les liens internes des articles (continuer dans l’atlas”)
  (pas une saisie dans le BO, on a déjà l'info il faut juste l'afficher)

**Comment by delphinelrcl** [comment]
Quand on clique sur un un lien externe dans un article ou focus, une nouvelle fenêtre doit s'ouvrir.

**Comment by naholyr** [comment]
Reste à faire : la présentation des résultats de type carte/image avec affichage des sources

Note @jri-sp une réindexation est nécessaire pour faire fonctionner le filtre A-Z ``yarn es-index reindex resource``
